LoadModule security2_module /usr/local/apache2/modules/mod_security2.so

Timeout ${TIMEOUT}
LogLevel ${LOGLEVEL}
ErrorLog ${ERRORLOG}

# https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#secserversignature
SecServerSignature ${MODSEC_SERVER_SIGNATURE}

<IfModule reqtimeout_module>
  RequestReadTimeout header=${REQUEST_READ_TIMEOUT_HEADER},MinRate=${REQUEST_READ_TIMEOUT_HEADER_MIN_RATE} body=${REQUEST_READ_TIMEOUT_BODY},MinRate=${REQUEST_READ_TIMEOUT_BODY_MIN_RATE}
</IfModule>

# The "common" and "combined" formats are predefined
LogFormat ${APACHE_LOGFORMAT} modsec
LogFormat ${APACHE_METRICS_LOGFORMAT} metricslog
ErrorLogFormat ${APACHE_ERRORLOG_FORMAT}

CustomLog ${METRICSLOG} metricslog "env=!nologging"

Include /etc/modsecurity.d/setup.conf
